[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/app/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
